import type { Card, Deck, Player, LeaderboardEntry } from "@/types";

export const CARDS: Card[] = [
  { id: "1", name: "Goblin Barrel", rarity: "Epic", elixirCost: 3, type: "Spell", description: "Throw a barrel of Goblins anywhere on the map.", emoji: "🛢️", winRate: 54.2, usageRate: 18.4 },
  { id: "2", name: "Hog Rider", rarity: "Rare", elixirCost: 4, type: "Troop", description: "Fast melee troop that targets buildings.", emoji: "🐗", winRate: 55.1, usageRate: 22.7 },
  { id: "3", name: "Skeleton King", rarity: "Champion", elixirCost: 4, type: "Champion", description: "Champion who raises an undead army.", emoji: "💀", winRate: 53.8, usageRate: 12.3 },
  { id: "4", name: "Goblin Giant", rarity: "Epic", elixirCost: 6, type: "Troop", description: "Goblin Giant is slow but powerful.", emoji: "👹", winRate: 52.4, usageRate: 9.8 },
  { id: "5", name: "Electro Dragon", rarity: "Epic", elixirCost: 5, type: "Troop", description: "Stuns enemies with electric breath.", emoji: "⚡", winRate: 51.9, usageRate: 15.6 },
  { id: "6", name: "Miner", rarity: "Legendary", elixirCost: 3, type: "Troop", description: "Digs underground to any location.", emoji: "⛏️", winRate: 53.6, usageRate: 14.2 },
  { id: "7", name: "Mega Knight", rarity: "Legendary", elixirCost: 7, type: "Troop", description: "Jump-slams on deploy dealing massive area damage.", emoji: "🛡️", winRate: 50.8, usageRate: 11.9 },
  { id: "8", name: "Royal Delivery", rarity: "Common", elixirCost: 3, type: "Spell", description: "Delivers a soldier from above, dealing damage.", emoji: "📦", winRate: 52.1, usageRate: 8.4 },
  { id: "9", name: "Firecracker", rarity: "Common", elixirCost: 3, type: "Troop", description: "Launches rockets at close-range attackers.", emoji: "🎆", winRate: 51.7, usageRate: 16.8 },
  { id: "10", name: "Valkyrie", rarity: "Rare", elixirCost: 4, type: "Troop", description: "Tough melee fighter that spins at enemies.", emoji: "⚔️", winRate: 51.3, usageRate: 13.5 },
  { id: "11", name: "Tesla", rarity: "Common", elixirCost: 4, type: "Building", description: "Electric tower that goes underground when empty.", emoji: "🗼", winRate: 50.4, usageRate: 7.2 },
  { id: "12", name: "Barbarian Barrel", rarity: "Epic", elixirCost: 2, type: "Spell", description: "Roll a barrel with a powerful barbarian inside.", emoji: "🪣", winRate: 54.8, usageRate: 19.1 },
  { id: "13", name: "Skeleton Army", rarity: "Epic", elixirCost: 3, type: "Troop", description: "Summons an army of skeletons.", emoji: "💀", winRate: 52.9, usageRate: 10.7 },
  { id: "14", name: "Inferno Tower", rarity: "Rare", elixirCost: 5, type: "Building", description: "Increases damage the longer it fires.", emoji: "🔥", winRate: 51.5, usageRate: 9.3 },
  { id: "15", name: "Golden Knight", rarity: "Champion", elixirCost: 4, type: "Champion", description: "Dashes and chains damage to nearby enemies.", emoji: "⚜️", winRate: 54.5, usageRate: 13.8 },
  { id: "16", name: "Phoenix", rarity: "Legendary", elixirCost: 4, type: "Troop", description: "Revives as an egg when defeated.", emoji: "🐦‍🔥", winRate: 53.2, usageRate: 17.6 },
  { id: "17", name: "Goblin Cage", rarity: "Rare", elixirCost: 4, type: "Building", description: "Cage releases a brawler when attacked.", emoji: "🏰", winRate: 50.7, usageRate: 6.9 },
  { id: "18", name: "Little Prince", rarity: "Champion", elixirCost: 3, type: "Champion", description: "Summons guard troops for protection.", emoji: "👑", winRate: 53.9, usageRate: 15.4 },
  { id: "19", name: "Arrows", rarity: "Common", elixirCost: 3, type: "Spell", description: "Rains arrows dealing area damage.", emoji: "🏹", winRate: 51.1, usageRate: 12.8 },
  { id: "20", name: "Cannon Cart", rarity: "Rare", elixirCost: 5, type: "Troop", description: "Mobile cannon that deploys as a building.", emoji: "💣", winRate: 50.2, usageRate: 5.8 },
];

export const DECKS: Deck[] = [
  {
    id: "1",
    name: "Hog 2.6 Cycle",
    cards: [CARDS[1], CARDS[0], CARDS[11], CARDS[8], CARDS[18], CARDS[9], CARDS[10], CARDS[7]],
    avgElixir: 2.6,
    winRate: 57.3,
    archetype: "Cycle",
    author: "ProRoyale",
    trophyRange: "6000+",
    votes: 12483,
  },
  {
    id: "2",
    name: "Mega Knight Bait",
    cards: [CARDS[6], CARDS[0], CARDS[11], CARDS[12], CARDS[5], CARDS[8], CARDS[18], CARDS[3]],
    avgElixir: 3.8,
    winRate: 55.1,
    archetype: "Bait",
    author: "TopLadder",
    trophyRange: "7000+",
    votes: 9821,
  },
  {
    id: "3",
    name: "Goblin Giant Sparky",
    cards: [CARDS[3], CARDS[4], CARDS[5], CARDS[1], CARDS[13], CARDS[16], CARDS[9], CARDS[7]],
    avgElixir: 4.1,
    winRate: 54.8,
    archetype: "Beatdown",
    author: "ElixirMaster",
    trophyRange: "8000+",
    votes: 7654,
  },
  {
    id: "4",
    name: "Graveyard Control",
    cards: [CARDS[13], CARDS[6], CARDS[4], CARDS[9], CARDS[19], CARDS[16], CARDS[12], CARDS[2]],
    avgElixir: 4.6,
    winRate: 53.9,
    archetype: "Control",
    author: "DefenseKing",
    trophyRange: "7500+",
    votes: 6234,
  },
  {
    id: "5",
    name: "Phoenix Bridge Spam",
    cards: [CARDS[15], CARDS[5], CARDS[1], CARDS[14], CARDS[9], CARDS[17], CARDS[7], CARDS[11]],
    avgElixir: 3.9,
    winRate: 55.7,
    archetype: "Bridge Spam",
    author: "RushMaster",
    trophyRange: "9000+",
    votes: 8901,
  },
  {
    id: "6",
    name: "Skeleton King Cycle",
    cards: [CARDS[2], CARDS[11], CARDS[0], CARDS[8], CARDS[18], CARDS[12], CARDS[9], CARDS[7]],
    avgElixir: 3.1,
    winRate: 56.2,
    archetype: "Cycle",
    author: "CyclePro",
    trophyRange: "6500+",
    votes: 5678,
  },
];

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, previousRank: 1, player: { tag: "#2PQCRQ9LG", name: "ReaperKing", trophies: 9842, bestTrophies: 9842, arena: "Ultimate Champion", wins: 18234, losses: 4521, level: 14, starPoints: 198400, cards: CARDS.slice(0,8) } },
  { rank: 2, previousRank: 3, player: { tag: "#9YQJJQYG2", name: "IceCrown", trophies: 9801, bestTrophies: 9812, arena: "Ultimate Champion", wins: 21453, losses: 5234, level: 14, starPoints: 212300, cards: CARDS.slice(0,8) } },
  { rank: 3, previousRank: 2, player: { tag: "#8LLQCGJUY", name: "TitanBlade", trophies: 9788, bestTrophies: 9820, arena: "Ultimate Champion", wins: 16789, losses: 3987, level: 14, starPoints: 177800, cards: CARDS.slice(0,8) } },
  { rank: 4, previousRank: 5, player: { tag: "#PCRUU9Y2Q", name: "ElixirGod", trophies: 9764, bestTrophies: 9764, arena: "Ultimate Champion", wins: 22134, losses: 6421, level: 14, starPoints: 234100, cards: CARDS.slice(0,8) } },
  { rank: 5, previousRank: 4, player: { tag: "#LLUY2PCRU", name: "ShadowWarden", trophies: 9751, bestTrophies: 9780, arena: "Ultimate Champion", wins: 14567, losses: 3210, level: 14, starPoints: 156700, cards: CARDS.slice(0,8) } },
  { rank: 6, previousRank: 8, player: { tag: "#2YJJQCRQ9", name: "VortexKnight", trophies: 9732, bestTrophies: 9745, arena: "Ultimate Champion", wins: 19876, losses: 5123, level: 14, starPoints: 201200, cards: CARDS.slice(0,8) } },
  { rank: 7, previousRank: 6, player: { tag: "#LG9PQCRQ2", name: "StarForge", trophies: 9718, bestTrophies: 9730, arena: "Ultimate Champion", wins: 17234, losses: 4321, level: 14, starPoints: 184500, cards: CARDS.slice(0,8) } },
  { rank: 8, previousRank: 10, player: { tag: "#UJYCLLQCG", name: "CrownHunter", trophies: 9699, bestTrophies: 9710, arena: "Ultimate Champion", wins: 20345, losses: 5678, level: 14, starPoints: 219800, cards: CARDS.slice(0,8) } },
  { rank: 9, previousRank: 7, player: { tag: "#2QCRQPYG9", name: "IronLegion", trophies: 9685, bestTrophies: 9700, arena: "Ultimate Champion", wins: 15678, losses: 3890, level: 14, starPoints: 167300, cards: CARDS.slice(0,8) } },
  { rank: 10, previousRank: 9, player: { tag: "#YQJJQG2Y9", name: "NightFury", trophies: 9671, bestTrophies: 9690, arena: "Ultimate Champion", wins: 13456, losses: 3012, level: 14, starPoints: 145600, cards: CARDS.slice(0,8) } },
];

export const SAMPLE_PLAYER: Player = {
  tag: "#2PQCRQ9LG",
  name: "RoyalRaider",
  trophies: 8234,
  bestTrophies: 8756,
  arena: "Master I",
  clan: "Elite Destroyers",
  role: "Co-Leader",
  wins: 14823,
  losses: 5234,
  level: 13,
  starPoints: 142800,
  rank: 1240,
  cards: CARDS.slice(0, 12),
  favoriteCard: CARDS[1],
};
